platform: linux/arm64

pipeline:
  build:
    image: ubuntu-dev
    commands:
      - meson build --prefix="`pwd`/prefix"
      - ninja -C build
      - ninja -C build install
  fetch-testbins:
    image: ubuntu-dev
    commands:
      - cd test
      - make bins
  unit-test:
    image: ubuntu-dev
    commands:
      - pip install --user 'git+https://github.com/rizinorg/rz-pipe#egg=rzpipe&subdirectory=python'
      - ninja -C build test
  rz-test:
    image: ubuntu-dev
    commands:
      - pip install --user 'git+https://github.com/rizinorg/rz-pipe#egg=rzpipe&subdirectory=python'
      - export PATH="`pwd`/prefix/bin:$PATH"
      - cd test
      - rz-test -L
