platform: linux/arm64

pipeline:
  build:
    image: ubuntu
    commands:
      - apt-get update > /dev/null
      - DEBIAN_FRONTEND=noninteractive apt-get -qqy --no-install-recommends install build-essential git python3-pip cmake make > /dev/null
      - pip install meson==0.62.0 ninja==1.10.2.3
      - pip install --user 'git+https://github.com/rizinorg/rz-pipe#egg=rzpipe&subdirectory=python'
      - meson build --prefix="`pwd`/prefix"
      - ninja -C build
      - ninja -C build install
  fetch-testbins:
    image: ubuntu
    commands:
      - cd test
      - make bins
  unit-test:
    image: ubuntu
    commands:
      - ninja -C build test
  rz-test:
    image: ubuntu
    commands:
      - export PATH="`pwd`/prefix/bin:$PATH"
      - cd test
      - rz-test -L
